# properties of email
email:
  prod:
    smtp:
      username:
      password:
    subject:
    from:
    to:
    cc:

# structure of report table in email
header:
    report_name:
    extras_information:

table:
    headers:
    highlight_index: